/// <reference path='../typings/angularjs/angular.d.ts' />
/// <reference path='../typings/angularjs/angular-mocks.d.ts' />
/// <reference path='../typings/angularjs/angular-resource.d.ts' />
/// <reference path='../typings/jasmine/jasmine.d.ts' />
/// <reference path='app.ts' />
/// <reference path='data/data.service.ts' />
/// <reference path='data/resources.factory.ts' />
/// <reference path='artist/artist-list.directive.ts' />
/// <reference path='artist/artist.model.ts' />
/// <reference path='album/album.model.ts' />
/// <reference path='album/album-list.directive.ts' />
//# sourceMappingURL=_references.js.map